spring:
  main:
    web-application-type: none

  datasource:
    url: jdbc:mysql://localhost:3306/learndb
    username: root
    password: Seriouscommander1
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
